set_property SRC_FILE_INFO {cfile:C:/SRIP2/projectnew/test8opti/constraints.xdc rfile:../../../constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 5.000 -name clk -waveform {0.000 2.500} [get_ports clk]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports resetn]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.000 [all_inputs]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.200 [all_inputs]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -max 1.000 [all_outputs]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -min 0.200 [all_outputs]
